### ISSUE TITLE
Link text is... not ideal

### ISSUE THREAD

**Issue by alanocallaghan** [VallejosGroup/OurWebsite#10]
Not sure where this comes from but grep usually helps

![hugo_text](https://user-images.githubusercontent.com/10779688/84778341-c5885900-afda-11ea-8a75-d59add476de6.png)

**Comment by nathansam** [comment]
Looks like the meta data can be updated

https://github.com/VallejosGroup/OurWebsite/blame/master/themes/hugo-universal-theme-cata/README.md#L390-L399

**Comment by alanocallaghan** [comment]
Yeah I got there in the end, also added some keywords. It also shows up on google, oops :D
