### ISSUE TITLE
Publications page

### ISSUE THREAD

**Issue by alanocallaghan** [VallejosGroup/OurWebsite#3]
Is there a way to separate main pubs from side projects?

Maybe just highlight authors from the group and let people judge.
Or
"Primary" and "other" (though this can be slightly muddy).

I slightly prefer the latter for now at least

**Comment by alanocallaghan** [comment]
Probably pretty easy to write JS that greps for and bolds author names. Just need a dictionary of author names in various formats (J Doe; Doe, J etc).

**Comment by catavallejos** [comment]
perhaps a temporary solution is to add an asterisk to denote group members?

**Comment by alanocallaghan** [comment]
Simple solutions never stopped me from over-engineering things :) I'll have a go at it this evening

**Comment by catavallejos** [comment]
🤣
