### ISSUE TITLE
blog & bloglogo entries for  members.

### ISSUE THREAD

**Issue by nathansam** [VallejosGroup/OurWebsite#7]
Would it be possible to add ``blog:`` and ``bloglogo`` keys for members? At the moment I am using the ``scholar`` and ``scholarlogo`` keys to link to my blog (I have not pushed the changes to GitHub.io presently) but it would be great to have a dedicated blog options if that is possible. Unfortunately I am not familiar enough with Hugo to be able to figure out how to add keys for the .yml files for members.

**Comment by alanocallaghan** [comment]
Post an svg logo and I'll add it

**Comment by alanocallaghan** [comment]
Actually I'm sort of unsure why we need the logo keys tbh, surely we always want to use the same ones?

**Comment by alanocallaghan** [comment]
87d3ee8

**Comment by nathansam** [comment]
Thanks!
