### ISSUE TITLE
Karla's image isn't loading

### ISSUE THREAD

**Issue by nathansam** [VallejosGroup/OurWebsite#9]
Karla's image isn't loading when I visit the people page

**Comment by alanocallaghan** [comment]
985c367

**Comment by alanocallaghan** [comment]
Eh... https://github.com/VallejosGroup/VallejosGroup.github.io/commit/985c367cd2c6b2eed3e02a3203c687b9cd66208e

**Comment by catavallejos** [comment]
Thank you!
